mappings:
  DataObjectAsPage: arambalakjian\DataObjectAsPage\DataObjects\DataObjectAsPage
  VersionedDataObjectAsPage: arambalakjian\DataObjectAsPage\Decorators\VersionedDataObjectAsPage
  VersionedGridFieldDeleteAction: arambalakjian\DataObjectAsPage\Forms\VersionedGridFieldDeleteAction
  VersionedGridFieldDetailForm: arambalakjian\DataObjectAsPage\Forms\VersionedGridFieldDetailForm
  VersionedGridFieldDetailForm_ItemRequest: arambalakjian\DataObjectAsPage\Forms\VersionedGridFieldDetailForm_ItemRequest
  DataObjectAsPageAdmin: arambalakjian\DataObjectAsPage\ModelAdmin\DataObjectAsPageAdmin
  ModelAdminHtmlEditorField_Toolbar: arambalakjian\DataObjectAsPage\ModelAdmin\ModelAdminHtmlEditorField_Toolbar
  DataObjectAsPageHolder: arambalakjian\DataObjectAsPage\Pages\DataObjectAsPageHolder
  DataObjectAsPageHolderController: arambalakjian\DataObjectAsPage\Pages\DataObjectAsPageHolderController
